# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *
import sys
import AlbumGUI
import MusicGUI
import TrangchuGUI
import PlaylistGUI
import CategoryGUI
from Client import Client

import musicPer
class Ui_MusicPlayer(QMainWindow):
    def __init__(self):
                super().__init__()
                self.setupUi()
                self.is_bot_shown = False
                self.mg = MusicGUI.MusicGUI()
                self.lstMusic = self.mg.returnMusic()
                self.pg = PlaylistGUI.PlaylistGUI()
                self.listPlaylist = self.pg.returnPlaylist()
    def setupUi(self):
        self.resize(911, 630)
        self.centralwidget = QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.leftMenu = QGroupBox(parent=self.centralwidget)
        self.leftMenu.setGeometry(QtCore.QRect(0, 50, 171, 441))
        self.leftMenu.setObjectName("leftMenu")
        self.leftMenu.setStyleSheet("QGroupBox { background-color: #000000; }")
        #---btnTrangChu
        self.btnTrangchu = QPushButton(parent=self.leftMenu)
        self.btnTrangchu.setGeometry(QtCore.QRect(15, 15, 141, 61))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/house-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnTrangchu.setIcon(icon)
        self.btnTrangchu.setObjectName("btnTrangchu")
        #---btnMusic
        self.btnMusic = QPushButton(parent=self.leftMenu)
        self.btnMusic.setGeometry(QtCore.QRect(15, 91, 141, 61))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/music-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnMusic.setIcon(icon1)
        self.btnMusic.setObjectName("btnMusic")
        #---btnPlaylist
        self.btnPlaylist = QPushButton(parent=self.leftMenu)
        self.btnPlaylist.setGeometry(QtCore.QRect(15, 167, 141, 61))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/record-vinyl-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnPlaylist.setIcon(icon2)
        self.btnPlaylist.setObjectName("btnAlbum")
        #---
        
        # self.bot = QGroupBox(parent=self.centralwidget)
        # self.bot.setGeometry(QtCore.QRect(0, 490, 911, 101))
        # self.bot.setTitle("")
        # self.bot.setObjectName("bot")
        # #---btnPlay
        # self.btnPlay = QPushButton(parent=self.bot)
        # self.btnPlay.setGeometry(QtCore.QRect(400, 50, 41, 41))
        # self.icon4 = QtGui.QIcon()
        # self.icon4.addPixmap(QtGui.QPixmap("img/play-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        # self.btnPlay.setIcon(self.icon4)
        # self.btnPlay.setText("")
        # self.btnPlay.setObjectName("btnPlay")
        # self.icon7 = QtGui.QIcon()
        # self.icon7.addPixmap(QtGui.QPixmap("img/pause-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        # #---btnPrev
        # self.btnPrev = QPushButton(parent=self.bot)
        # self.btnPrev.setGeometry(QtCore.QRect(350, 50, 41, 41))
        # icon5 = QtGui.QIcon()
        # icon5.addPixmap(QtGui.QPixmap("img/backward-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        # self.btnPrev.setIcon(icon5)
        # self.btnPrev.setText("")
        # self.btnPrev.setObjectName("btnPrev")
        # #---btnNexxt
        # self.btnNexxt = QPushButton(parent=self.bot)
        # self.btnNexxt.setGeometry(QtCore.QRect(450, 50, 41, 41))
        # icon6 = QtGui.QIcon()
        # icon6.addPixmap(QtGui.QPixmap("img/forward-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        # self.btnNexxt.setIcon(icon6)
        # self.btnNexxt.setText("")
        # self.btnNexxt.setObjectName("btnNexxt")
        # #---




        # self.lbNamesone = QLabel(parent=self.bot)
        # self.lbNamesone.setGeometry(QtCore.QRect(20, 30, 161, 41))
        # self.lbNamesone.setText("")
        # self.lbNamesone.setObjectName("lbNamesone")
        # self.sliderTime = QSlider(parent=self.bot)
        # self.sliderTime.setGeometry(QtCore.QRect(260, 10, 321, 22))
        # self.sliderTime.setOrientation(QtCore.Qt.Orientation.Horizontal)
        # self.sliderTime.setObjectName("sliderTime")
        # self.lbTimeplay = QLabel(parent=self.bot)
        # self.lbTimeplay.setGeometry(QtCore.QRect(210, 10, 41, 16))
        # self.lbTimeplay.setObjectName("lbTimeplay")
        # self.lbTimetong = QLabel(parent=self.bot)
        # self.lbTimetong.setGeometry(QtCore.QRect(590, 10, 41, 16))
        # self.lbTimetong.setObjectName("lbTimetong")

        self.scrollArea = QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(170, 50, 742, 441))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 742, 439))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.layout = QGridLayout()
        self.layout.setHorizontalSpacing(0)
        self.layout.setVerticalSpacing(0)
        self.scrollAreaWidgetContents.setLayout(self.layout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        
        self.groupBox = QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 911, 51))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox.setStyleSheet("QGroupBox { background-color: #0000ff; }")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(parent=self.centralwidget)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 911, 21))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(parent=self.centralwidget)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        #-------------------------Trang
        self.pagesPn = QFrame(parent=self.scrollArea)
        self.pagesPn.setGeometry(QtCore.QRect(0, 0, 742, 440))
        self.pagesPn.setStyleSheet("background-color: #F6F6F6;\n"
"")
        self.pagesPn.setFrameShape(QFrame.Shape.StyledPanel)
        self.pagesPn.setFrameShadow(QFrame.Shadow.Raised)
        self.pagesPn.setObjectName("pagesPn")

        self.pagesWidget = QStackedWidget(parent=self.pagesPn)
        self.pagesWidget.setGeometry(QtCore.QRect(0, 0, 742, 550))
        self.pagesWidget.setObjectName("pagesWidget")
        self.categoryGUI = CategoryGUI.CategoryGUI()
        self.categoryGUI.setObjectName("TrangchuGUI")
        self.pagesWidget.addWidget(self.categoryGUI)
        self.musicGUI = MusicGUI.MusicGUI()
        self.musicGUI.setObjectName("MusicGUI")
        self.pagesWidget.addWidget(self.musicGUI)
        self.playlistGUI = PlaylistGUI.PlaylistGUI()
        self.playlistGUI.setObjectName("PlaylistGUI")
        self.pagesWidget.addWidget(self.playlistGUI)
        self.setCentralWidget(self.centralwidget)
    #----------------------------gan link cho btn
        self.btnTrangchu.clicked.connect(self.handleBtnCat)
        self.btnMusic.clicked.connect(self.handleBtnMus)
        self.btnPlaylist.clicked.connect(self.handleBtnPlaylist)

    # # Kết nối sự kiện clicked với hàm on_clicked()
    #     self.btnPlay.clicked.connect(self.on_clicked)

    # def on_clicked(self):
    # # Thay đổi icon khi QPushButton được nhấn
    #     if self.btnPlay.icon() == self.icon4:
    #         self.btnPlay.setIcon(self.icon7)
    #     else:
    #         self.btnPlay.setIcon(self.icon4)

    def handleBtnPlaylist(self):
        self.clearPagesWidget()
        self.toPlaylist()
    def handleBtnCat(self):
        self.clearPagesWidget()
        self.toTrangchu()
    def handleBtnMus(self):
        self.clearPagesWidget()
        self.toMusic()
    def clearPagesWidget(self):
        while self.pagesWidget.count():
            widget = self.pagesWidget.widget(0)
            self.pagesWidget.removeWidget(widget)
            widget.deleteLater()


    def retranslateUi(self):
        self.setWindowTitle("MusicPlayer")
        self.btnTrangchu.setText("Category")
        self.btnMusic.setText("Music")
        self.btnPlaylist.setText("Playlist")
        # self.lbTimeplay.setText("00:00")
        # self.lbTimetong.setText("00:00")
    def toTrangchu(self):
        self.categoryGUI = CategoryGUI.CategoryGUI()
        self.categoryGUI.setObjectName("TrangchuGUI")
        self.pagesWidget.addWidget(self.categoryGUI)
        self.pagesWidget.setCurrentWidget(self.categoryGUI)

    def toMusic(self):
        self.musicGUI = MusicGUI.MusicGUI()
        self.musicGUI.setObjectName("MusicGUI")
        self.pagesWidget.addWidget(self.musicGUI)
        self.pagesWidget.setCurrentWidget(self.musicGUI)

    def toPlaylist(self):
        self.playlistGUI = PlaylistGUI.PlaylistGUI()
        self.playlistGUI.setObjectName("PlaylistGUI")
        self.pagesWidget.addWidget(self.playlistGUI)
        self.pagesWidget.setCurrentWidget(self.playlistGUI)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    ui = Ui_MusicPlayer()
    ui.show()
    sys.exit(app.exec())
